# Generated by Django 6.0.6 on 2026-06-23 11:09

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('date', models.DateField(help_text='Publication date')),
                ('readTime', models.CharField(help_text='Estimated reading duration (e.g. 6 min read)', max_length=50)),
                ('summary', models.TextField(help_text='Brief text abstract shown on the grid card', max_length=300)),
                ('imageUrl', models.URLField(help_text='Post teaser header image URL', max_length=500)),
            ],
            options={
                'db_table': 'blog_posts',
            },
        ),
        migrations.CreateModel(
            name='ContactSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='info@polynexus.com', max_length=254)),
                ('phone', models.CharField(default='+91 9226318818', max_length=50)),
                ('address', models.CharField(default='Nagpur, Maharashtra', max_length=255)),
                ('est_response', models.CharField(default='EST RESPONSE TIME: < 15 MINUTES', max_length=255)),
            ],
            options={
                'verbose_name': 'Contact Settings',
                'verbose_name_plural': 'Contact Settings',
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField(help_text='Detailed markdown/text answer block')),
            ],
            options={
                'db_table': 'faqs',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ai', 'AI'), ('devtools', 'Developer Tools'), ('infra', 'Infrastructure')], help_text='Project category (ai, devtools, or infra)', max_length=20)),
                ('desc', models.TextField(help_text='Detailed description of the business/technical solution')),
                ('metric', models.CharField(help_text='High-impact metric value (e.g. 0.15ms, 100%)', max_length=50)),
                ('metricLabel', models.CharField(help_text='Label explaining the metric value (e.g. Vector Resolution)', max_length=100)),
                ('icon', models.CharField(help_text='Lucide icon reference name (e.g. Cpu, Database)', max_length=50)),
                ('tech', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), help_text='Array of technologies used')),
                ('image', models.URLField(help_text='URL path to the dashboard mockup screenshot image', max_length=500)),
                ('file', models.CharField(blank=True, help_text='Shell file label shown in the Hero mockup header (e.g. cognitive-query-api.sh)', max_length=100, null=True)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.CharField(help_text='URL-safe slug or primary key (e.g. design, governance)', max_length=50, primary_key=True, serialize=False)),
                ('icon', models.CharField(help_text='Lucide react icon name (e.g. Zap, Database)', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('shortDesc', models.TextField(help_text='Short description displayed directly in the grid card', max_length=250)),
                ('fullDesc', models.TextField(help_text='In-depth description shown inside the engineering modal specsheet')),
                ('features', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), help_text='List of key integration pillars / bullet points')),
                ('specs', models.JSONField(help_text="Key-value pairs representing engineering specs (e.g. {'Speed': '100% Core Performance'})")),
            ],
            options={
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='Job title (e.g. VP of Platform Engineering)', max_length=100)),
                ('company', models.CharField(help_text='Company name (e.g. NovusAI)', max_length=100)),
                ('content', models.TextField(help_text='Testimonial narrative content text', max_length=500)),
                ('rating', models.PositiveSmallIntegerField(help_text='Numerical rating score (typically 5)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('avatar', models.URLField(help_text="Reviewer's profile photo URL", max_length=500)),
            ],
            options={
                'db_table': 'testimonials',
            },
        ),
    ]
