# Generated by Django 6.0.6 on 2026-06-23 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_admintoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='CO-CREATING DIGITAL EXCELLENCE', max_length=255)),
                ('title_prefix', models.CharField(default='Building ', max_length=255)),
                ('title_highlight', models.CharField(default='custom software', max_length=255)),
                ('title_suffix', models.CharField(default=' to maximize your business impact', max_length=255)),
                ('subtitle', models.TextField(default='We deeply understand your unique operational bottlenecks and design tailored engineering pathways to solve them. Skip rigid, off-the-shelf limitations and scale with bespoke solutions built strictly around your users, your workflows, and your long-term goals.')),
                ('cta1_text', models.CharField(default='Get Your Custom Solution', max_length=100)),
                ('cta1_link', models.CharField(default='#contact', max_length=100)),
                ('cta2_text', models.CharField(default='View Our Services', max_length=100)),
                ('cta2_link', models.CharField(default='#services', max_length=100)),
                ('trust_indicators', models.JSONField(default=list, help_text='List of dicts containing label, value, icon, color')),
            ],
            options={
                'verbose_name': 'Hero Settings',
                'verbose_name_plural': 'Hero Settings',
                'db_table': 'hero_settings',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='image_data',
            field=models.BinaryField(blank=True, help_text='Binary screenshot image data', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_mime_type',
            field=models.CharField(blank=True, help_text='Mime type of the binary image', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.URLField(blank=True, help_text='URL path to the dashboard mockup screenshot image', max_length=500, null=True),
        ),
    ]
