# Generated by Django 6.0.6 on 2026-06-23 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_herosetting_project_image_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('enterprise', 'Enterprise Management'), ('logistics', 'Custom Operations & Logistics'), ('saas', 'Productivity & B2B SaaS')], help_text='Project category (enterprise, logistics, or saas)', max_length=20),
        ),
    ]
