# Generated by Django 6.0.6 on 2026-06-24 09:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_project_challenges_project_longdesc_project_results'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='challenges',
        ),
        migrations.AddField(
            model_name='project',
            name='benefits',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='List of key benefits and value delivered', null=True),
        ),
    ]
