# Generated by Django 6.0.6 on 2026-06-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_remove_project_challenges_project_benefits'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price',
            field=models.CharField(blank=True, help_text='Starting price of the project (e.g. ₹599 / month)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='price_detail_html',
            field=models.TextField(blank=True, help_text='Raw HTML table/content for detailed pricing modal', null=True),
        ),
    ]
