# Generated by Django 6.0.6 on 2026-06-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_project_price_project_price_detail_html'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('polynexus', 'Polynexus Products'), ('custom', 'Custom Software')], help_text='Project category (polynexus or custom)', max_length=20),
        ),
    ]
