# Generated by Django 6.0.6 on 2026-06-25 10:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_alter_project_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='enterprise_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Enterprise plan features list', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='premium_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Premium plan features list', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='premium_original_price',
            field=models.CharField(blank=True, default='', help_text='Premium original price (e.g. 3499)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='premium_price',
            field=models.CharField(blank=True, default='', help_text='Premium discounted price (e.g. 2999)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='standard_features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Standard plan features list', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='standard_original_price',
            field=models.CharField(blank=True, default='', help_text='Standard original price (e.g. 1499)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='standard_price',
            field=models.CharField(blank=True, default='', help_text='Standard discounted price (e.g. 1249)', max_length=50, null=True),
        ),
    ]
