# Generated by Django 6.0.6 on 2026-06-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_project_enterprise_features_project_premium_features_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('replied', models.BooleanField(default=False)),
                ('reply_message', models.TextField(blank=True, default='', null=True)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
